export const GET_COLLEGE_REQUEST = "GET_COLLEGE_DATA_REQUEST";
export const GET_COLLEGE_SUCCESS = "ADD_COLLEGE_DATA_SUCCESS";
export const GET_COLLEGE_FAILURE = "GET_COLLEGE_DATA_FAILURE"

export const GET_USER_REQUEST = "GET_USER_DATA_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_FAILURE = "GET_COLLEGE_DATA_FAILURE";


export const CHANGE_LOGIN_STATUS = "CHANGE_LOGIN_STATUS";



export const CHANGE_THEME = "CHANGE_THEME";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";
