export const GET_COLLEGE_REQUEST = "GET_COLLEGE_DATA_REQUEST";
export const GET_COLLEGE_SUCCESS = "ADD_COLLEGE_DATA_SUCCESS";
export const GET_COLLEGE_FAILURE = "GET_COLLEGE_DATA_FAILURE";

export const GET_USER_REQUEST = "GET_USER_DATA_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_DATA_SUCCESS";
export const GET_USER_FAILURE = "GET_COLLEGE_DATA_FAILURE";

export const CHANGE_LOGIN_SUCCESS = "CHANGE_LOGIN_SUCCESS";
export const CHANGE_LOGIN_REQUEST = "CHANGE_LOGIN_REQUEST";
export const CHANGE_LOGIN_STATUS = "CHANGE_LOGIN_STATUS";
export const CHANGE_LOGIN_LOGOUT = "CHANGE_LOGIN_LOGOUT";

export const noOfItemsPerPage = 10;
export const GET_COURSES_REQUEST = "GET_COURSES_REQUEST";
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const GET_COURSES_FAILURE = "GET_COURSES_FAILURE";
export const UPDATE_CART_PRICE = "UPDATE_CART_PRICE";
export const SORT_COURSES = "SORT_COURSES";

export const CHANGE_THEME = "CHANGE_THEME";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_FROM_CART = "DELETE_FROM_CART";

// export const LOGIN_TO_PAGE = "LOGIN";
// export const LOGOUT_FROM_PAGE = "LOGOUT";
export const ADD_TO_REGISTERED_COURSES = "ADD_TO_REGISTERED_COURSES";
export const DELETE_FROM_REGISTERED_COURSES = "DELETE_FROM_REGISTERED_COURSES";

export const url = "https://course-json-server-data.onrender.com";
// export const url = "http://localhost:8080";

export const RESET_CART = "RESET_CART";
